name: "Dependabot Automerge - Action"

on:
  push:
    branches:
    - production

  pull_request:
    branches:
    - production

  workflow_dispatch:

jobs:
  worker:
    name: 'Dependabot'
    
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: automerge
        uses: actions/github-script@v6.2.0
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
